name: CI (indexing)

on:
  push:
    paths:
      - 'Gemfile.lock'
      - 'lib/ruby_indexer/**'
  pull_request:
    paths:
      - 'Gemfile.lock'
      - 'lib/ruby_indexer/**'

jobs:
  indexing_sanity_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Ruby
        uses: ruby/setup-ruby@472790540115ce5bd69d399a020189a8c87d641f # v1.247.0
        with:
          bundler-cache: true

      - name: Index Top 100 Ruby gems
        run: bundle exec rake index:topgems
