name: CI (indexing)

on:
  push:
    paths:
      - 'Gemfile.lock'
      - 'lib/ruby_indexer/**'
  pull_request:
    paths:
      - 'Gemfile.lock'
      - 'lib/ruby_indexer/**'

jobs:
  indexing_sanity_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Ruby
        uses: ruby/setup-ruby@44511735964dcb71245e7e55f72539531f7bc0eb # v1.257.0
        with:
          bundler-cache: true

      - name: Index Top 100 Ruby gems
        run: bundle exec rake index:topgems
