name: Publish docs

on:
  push:
    branches: [main]
    paths:
      - 'jekyll/**'
      - '.github/workflows/publish_docs.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'Shopify/ruby-lsp'
    name: Publish documentation website
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Ruby
        uses: ruby/setup-ruby@cb0fda56a307b8c78d38320cd40d9eb22a3bf04e # v1.242.0
        with:
          bundler-cache: true
          working-directory: ./jekyll

      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Generate documentation
        working-directory: ./jekyll
        run: bundle exec jekyll build

      - name: Commit to gh-pages
        run: |
          git add docs -f
          git commit -m "Publish website $(git log --format=format:%h -1)"
          git push --force origin main:gh-pages
